### ISSUE TITLE
controller support?

### ISSUE THREAD

**Issue by coreybruce** [vmbatlle/super-mario-kart#62]
Hey there, just wondering if controller support will be added to the game at all?

**Comment by diegoroyo** [comment]
We do not have any current plans to extend this project at the moment, sorry. You can try to use an external tool to map controller inputs to keyboard inputs. Analog inputs are not supported by the game in its current state, but pull requests are welcome :)

**Comment by coreybruce** [comment]
Ok thank you for your time :)
